-- CALCULATE THE TOTAL REVENUE GENERATED FROM PIZZA SALES.
SELECT SUM(ORDERS_DETAILS.QUANTITY*PIZZAS.PRICE) 
FROM ORDERS_DETAILS JOIN PIZZAS 
ON PIZZAS.PIZZA_ID=ORDERS_DETAILS.PIZZA_ID;

-- IDENTIFY THE HIGEST-PRICED PIZZA
SELECT PIZZA_TYPES.NAME , PIZZAS.PRICE FROM PIZZA_TYPES JOIN PIZZAS 
ON PIZZA_TYPES.PIZZA_TYPE_ID=PIZZAS.PIZZA_TYPE_ID
ORDER BY PIZZAS.PRICE DESC LIMIT 1;

-- IDENTIFY THE MOST COMMON PIZZA SIZE ORDERED
SELECT PIZZAS.SIZE,COUNT(ORDERS_DETAILS.ORDER_DETAILS_ID) FROM PIZZAS JOIN ORDERS_DETAILS 
ON PIZZAS.PIZZA_ID=ORDERS_DETAILS.PIZZA_ID GROUP BY PIZZAS.SIZE ORDER BY COUNT(ORDERS_DETAILS.ORDER_DETAILS_ID) DESC ;

-- LIST THE TOP 5 MOST ORDERED PIZZA TYPES
-- ALONG WITH THEIR QUANTITIES.

SELECT 
    PIZZA_TYPES.NAME, SUM(ORDERS_DETAILS.QUANTITY) AS QUANTITY  
FROM 
PIZZA_TYPES 
	JOIN 
PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID 
    JOIN 
ORDERS_DETAILS ON ORDERS_DETAILS.PIZZA_ID= PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME 
ORDER BY QUANTITY DESC 
LIMIT 5;

