-- Calculate the percentage contribution of each pizza type to total revenue.
SELECT PIZZA_TYPES.CATEGORY, 
ROUND((SUM(ORDERS_DETAILS.QUANTITY * PIZZAS.PRICE) / (SELECT ROUND(SUM(ORDERS_DETAILS.QUANTITY*PIZZAS.PRICE),2) AS TOTAL_SALES 
                                                FROM ORDERS_DETAILS JOIN PIZZAS ON PIZZAS.PIZZA_ID= ORDERS_DETAILS.PIZZA_ID) )*100,2) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS ON ORDERS_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.CATEGORY ORDER BY REVENUE DESC; 


-- Analyze the cumulative revenue generated over time.
SELECT ORDER_DATE,SUM(REVENUE) OVER(ORDER BY ORDER_DATE) AS CUM_REVENUE 
FROM
(SELECT  ORDERS.ORDER_DATE,
SUM(ORDERS_DETAILS.QUANTITY * PIZZAS.PRICE)AS REVENUE
FROM ORDERS_DETAILS JOIN PIZZAS
ON ORDERS_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN ORDERS ON ORDERS.ORDER_ID = ORDERS_DETAILS.ORDER_ID
GROUP BY ORDERS.ORDER_DATE) AS SALES;


-- Determine the top 3 most ordered pizza types based on revenue for each pizza category.
SELECT PIZZA_TYPES.CATEGORY,PIZZA_TYPES.NAME,
SUM((ORDERS_DETAILS.QUANTITY)*PIZZAS.PRICE) AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID =PIZZAS.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS
ON ORDERS_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.CATEGORY,PIZZA_TYPES.NAME;
